# Generated by Django 4.2.7 on 2025-03-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to='users.account')),
            ],
            options={
                'verbose_name': 'Facebook Page',
                'verbose_name_plural': 'Facebook Pages',
            },
        ),
        migrations.CreateModel(
            name='InstagramBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=2000, null=True)),
                ('follows_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_account', to='facebook_service.facebookpage')),
            ],
            options={
                'verbose_name': 'Instagram Business Account',
                'verbose_name_plural': 'Instagram Business Accounts',
            },
        ),
        migrations.CreateModel(
            name='InstagramInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('follower_count', models.PositiveIntegerField()),
                ('reach', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('profile_views', models.PositiveIntegerField()),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='facebook_service.instagrambusinessaccount')),
            ],
            options={
                'verbose_name': 'Instagram Insights',
                'verbose_name_plural': 'Instagram Insights',
                'indexes': [models.Index(fields=['date'], name='facebook_se_date_ba5a33_idx')],
                'unique_together': {('instagram_account', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='instagrambusinessaccount',
            index=models.Index(fields=['instagram_id'], name='facebook_se_instagr_af036e_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrambusinessaccount',
            index=models.Index(fields=['username'], name='facebook_se_usernam_d02fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookpage',
            index=models.Index(fields=['page_id'], name='facebook_se_page_id_e53d5d_idx'),
        ),
    ]
