# Generated by Django 4.2.7 on 2025-03-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_scope_id', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('follows_count', models.IntegerField(blank=True, null=True)),
                ('has_profile_pic', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('media_count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
            options={
                'verbose_name': 'Facebook User',
                'verbose_name_plural': 'Facebook Users',
                'indexes': [models.Index(fields=['username'], name='instagram_s_usernam_c89b1e_idx')],
            },
        ),
    ]
